/*let inputJoueur = document.getElementById("inputEcriture")
console.log(inputJoueur)
let boutonValider = document.getElementById("btnValiderMot")
console.log(boutonValider)
let zoneProposition = document.querySelector(".zoneProposition")
console.log(zoneProposition)
let zoneScoreSpan = document.querySelector(".zoneScore span")
console.log(zoneScoreSpan)
let listRadioButton = document.querySelectorAll(".optionSource input")
console.log(listRadioButton)*/
lancerJeu()